# Generated by Django 4.2.1 on 2023-06-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
