# Generated by Django 4.2.1 on 2023-06-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productcategory_show_on_homepage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tag',
            new_name='tags',
        ),
    ]
