# Generated by Django 4.2.1 on 2023-06-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='sub_heading',
            field=models.CharField(max_length=35),
        ),
    ]
