# Generated by Django 4.2.1 on 2023-06-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_slider_sub_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
