# Generated by Django 4.2.1 on 2023-06-23 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderdetails_vriation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='vriation',
            new_name='variation',
        ),
    ]
