# Generated by Django 4.2.1 on 2023-06-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_vriation_orderdetails_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Inprogress', 'Inprogress'), ('Dispatch', 'Dispatch'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
